### ISSUE TITLE
Puppet 4 support

### ISSUE THREAD

**Issue by Herr-Herner** [voxpupuli/puppet-staging#67]
I made a very quick, but insufficient run of puppet-staging under Puppet 4 and so far everything looks good. Is puppet-staging compatible with Puppet 4 or can be made compatible with? The version requirement says that Puppet 4 is currently not supported.

**Comment by nanliu** [comment]
It's not widely tested, but probably works because the module is mostly native resources. Currently there are too many hurdles to run puppet 4 in travis.ci (I think there are numerous issues with rspec-puppet). I'll turn on future parser and if it compiles it most likely will be ok. Please provide feedback if you run into any problems.

**Comment by Herr-Herner** [comment]
Thank you very much for your quick response. I will keep you in touch.

**Comment by nanliu** [comment]
I remove the restrictions per #68, but will need more feedback.

**Comment by jyaworski** [comment]
We're now actively testing on Puppet 4, so I'm going to close this.
