### ISSUE TITLE
Path not fully qualified (Windows)

### ISSUE THREAD

**Issue by cdenneen** [voxpupuli/puppet-staging#98]
When running spec tests for compiling on Linux/OSX it complains about fully qualified path:

```
       error during compilation: Parameter path failed on File[C:\staging]: File paths must be fully qualified, not 'C:\staging' at ...
```

Has anyone found solution to this issue?
Might need to add some Windows specific spec tests to this module.

**Comment by nanliu** [comment]
TLDR, not much value unless you use windows as an unit test platform.

See example: https://github.com/voxpupuli/puppet-archive/blob/master/spec/unit/puppet/type/archive_spec.rb#L29-L58

However be aware this basically skips the windows test on Linux. It does not have the capability to exercise the two different path (i.e. travis.ci will only test linux). 

I would raise issue with Puppet Labs since fundamentally it requires patching of Puppet::Util.absolute_path? (since that method only cares about what OS you are running, not that rspec-puppet is trying to simulate windows via some facts).

**Comment by rgarrigue** [comment]
Any update on this topic ? Solution or decent workaround ? 

I'm interested in a way to solve the same issue for other puppet profiles & roles. As of now, I just commented `it { is_expected.to compile }` but a few issues went under the radar this way.

**Comment by GrammatonKlaric** [comment]
I have discovered that this issue only occurs if I have relationship functions for a file resource or exec resource with a `creates` parameter in the spec test. E.g. 
```ruby
is_expected.do contain_Exec('working').that_comes_before('File[C:\Windows]')
is_expected.to contain_File('C:\Windows')
```
or
```ruby
is_expected.do contain_Exec('working').that_comes_before('Exec[fails]')
is_expected.to contain_Exec('fails').with({"creates" => 'C:\Windows\mytestfile.txt'})
```

The above code will throw the issue, but simply having the below code will avoid the issue:
```ruby
is_expected.do contain_Exec('working')
is_expected.to contain_File('C:\Windows')
```
or
```ruby
is_expected.do contain_Exec('working')
is_expected.to contain_Exec('no longer failing').with({"creates" => 'C:\Windows\mytestfile.txt'})
```

Can anyone else duplicate this? Perhaps the root cause is in the relationship functions?

**Comment by ekohl** [comment]
This module is deprecated in favor of [puppet-archive](https://github.com/voxpupuli/puppet-archive) and as such won't receive any more updates.
